version: "3.9"
services:
  apirest:
    build: .
    ports:
      - "8084:80"
    links:
      - myBDIntegration
    networks:
      - net
  myBDIntegration:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=libreriaDB
      - MYSQL_ROOT_PASSWORD=nova
  phpMyAdmin:
    image: phpmyadmin
    ports: 
      - 8080:80
    environment:
      - PMA_HOST=myBDIntegration    
  jenkins:
    image: jenkins/jenkins:lts
    restart: unless-stopped
    privileged: true
    user: root
    ports:
      - 8082:8080
      - 50000:50000
    links:
      - apirest
    container_name: jenkins
    volumes:
      - $PWD/jenkins_data:/var/jenkins_home
      - //var/run/docker.sock:/var/run/docker.sock
      - //usr/local/bin/docker:/usr/local/bin/docker
    networks:
      - net
networks:
  net:

