version: "3.9"
services:
  apirest:
    build: .
    ports:
      - "8084:80"
    links:
      - myBDIntegration
  myBDIntegration:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=libreriaDB
      - MYSQL_ROOT_PASSWORD=nova
